Repository arimorc/air-react-forms, pull requests merged in 2021-07, with the labels that each got.

#7 Implemented standalone checkbox inputs and checkbox groups management.
  playground/src/SimpleForm.jsx
  src/hooks/useCheckboxGroup.jsx
  src/hooks/useForm.jsx
  src/index.js
  src/utils/inputTypeUtils.js
  src/validators/hasMaxChecked.js
  src/validators/hasMinChecked.js
  src/validators/index.js
  tests/hooks/useCheckboxGroup.test.js
  tests/hooks/useForm.test.js
  tests/testUtils/CheckboxGroupTestForm.jsx
  tests/testUtils/FieldArrayTestForm.jsx
  tests/utils/inputTypeUtils.test.js
  tests/validators/hasMaxChecked.test.js
  tests/validators/hasMinChecked.test.js
Labels: Priority : Medium, Status : Accepted, Type : Feature

#8 Written the first version of the library's README file.
  README.md
Labels: Priority : Low, Status : To review, Type : Documentation

#9 Implemented a hook to manage radio button groups.
  README.md
  playground/src/SimpleForm.jsx
  src/hooks/useCheckboxGroup.jsx
  src/hooks/useForm.jsx
  src/hooks/useRadioButtonGroup.jsx
  src/index.js
  src/validators/checkboxGroup/hasMaxChecked.js
  src/validators/checkboxGroup/hasMinChecked.js
  src/validators/index.js
  src/validators/radioButtonGroup/isRequired.js
  tests/hooks/useForm.test.js
  tests/hooks/useRadioButtonGroup.test.js
  tests/testUtils/RadioButtonGroupTestForm.jsx
  tests/validators/checkboxGroup/hasMaxChecked.test.js
  tests/validators/checkboxGroup/hasMinChecked.test.js
  tests/validators/radioButtonGroup/isRequired.test.js
Labels: Priority : Medium, Status : To review, Type : Feature

#11 Fix rollup configuration
  .np-config.json
  package.json
  rollup.config.js
  yarn.lock
Labels: Priority : Critical, Status : Accepted

#12 v1.0.0
  package.json
Labels: Status : Accepted

#13 Export the register function within formContext
  package.json
  src/hooks/useForm.jsx
Labels: Priority : Critical, Status : Accepted

#14 v1.1.0
  package.json
Labels: Status : Accepted
